export const endPoints = {
  AUTH: {
    LOGIN: '/auth/login',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
    REFRESH: '/auth/refresh',
  },
  ORGANIZATION: {
    BASE: '/organizations',
    GET_ALL: '/organizations',
    GET_BY_ID: (id: string) => `/organizations/${id}`,
    CREATE: '/organizations',
    UPDATE: (id: string) => `/organizations/${id}`,
    DELETE: (id: string) => `/organizations/${id}`,
    HARD_DELETE: (id: string) => `/organizations/${id}/hard`,
    ASSIGN_CUSTOM_SERVICES: (id: string) => `/organizations/${id}/custom-services`,
  },
  SERVICE_REQUEST_TEMPLATE: {
    BASE: '/service-request-templates',
    GET_ACTIVE_GENERAL: '/service-request-templates/active/general',
    GET_ACTIVE_SERVICE: (service: string) => `/service-request-templates/active/service/${service}`,
    GET_ALL: '/service-request-templates',
    GET_BY_ID: (id: string) => `/service-request-templates/${id}`,
    CREATE: '/service-request-templates',
    UPDATE: (id: string) => `/service-request-templates/${id}`,
  },
  CLIENT: {
    BASE: '/clients',
    GET_ALL: '/clients',
    GET_BY_ID: (id: string) => `/clients/${id}`,
    CREATE: '/clients',
    UPDATE: (id: string) => `/clients/${id}`,
    DELETE: (id: string) => `/clients/${id}`,
  },
  COMPANY: {
    BASE: '/companies',
    GET_ALL: '/companies',
    GET_BY_ID: (id: string) => `/companies/${id}`,
    CREATE: '/companies',
    UPDATE: (id: string) => `/companies/${id}`,
    DELETE: (id: string) => `/companies/${id}`,
    GET_BY_CLIENT: (clientId: string) => `/companies?clientId=${clientId}`,
    INCORPORATION: (companyId: string) => `/companies/${companyId}/incorporation`,
    KYC: (companyId: string) => `/companies/${companyId}/kyc`,
  },
  SERVICE_REQUEST: {
    BASE: '/service-requests',
    GET_ALL: '/service-requests',
    GET_BY_ID: (id: string) => `/service-requests/${id}`,
    UPDATE_STATUS: (id: string) => `/service-requests/${id}/status`,
  },
  CUSTOM_SERVICE: {
    BASE: '/custom-services',
    LIST: '/custom-services',
    GET_ACTIVE: '/custom-services/active',
    GET_BY_ID: (id: string) => `/custom-services/${id}`,
    CREATE: '/custom-services',
    UPDATE: (id: string) => `/custom-services/${id}`,
    PATCH_STATUS: (id: string) => `/custom-services/${id}/status`,
    DELETE: (id: string) => `/custom-services/${id}`,
  },
  ENGAGEMENT: {
    BASE: '/engagements',
    GET_ALL: '/engagements',
    GET_BY_ID: (id: string) => `/engagements/${id}`,
    CREATE: '/engagements',
    UPDATE: (id: string) => `/engagements/${id}`,
    UPDATE_STATUS: (id: string) => `/engagements/${id}/status`,
  },
  LIBRARY: {
    FOLDERS: '/library/folders',
    FOLDER_CONTENT: (id: string) => `/library/folders/${id}/content`,
    ROOTS: '/library/folders/roots',
    FOLDER_BY_ID: (id: string) => `/library/folders/${id}`,
    FILES: '/library/files',
    FILE_UPLOAD: '/library/files/upload',
    FILE_BY_ID: (id: string) => `/library/files/${id}`,
    FOLDER_DOWNLOAD: (id: string) => `/library/folders/${id}/download`,
  },
  NOTICE: {
    BASE: '/notices',
    GET_ALL: '/notices',
    GET_BY_ID: (id: string) => `/notices/${id}`,
    CREATE: '/notices',
    UPDATE: (id: string) => `/notices/${id}`,
    PATCH_STATUS: (id: string) => `/notices/${id}/status`,
    DELETE: (id: string) => `/notices/${id}`,
    GET_TODAY: '/notices/today',
  },
  INVOLVEMENT: {
    BASE: '/involvements',
    CREATE: '/involvements',
    UPDATE: (id: string) => `/involvements/${id}`,
    DELETE: (id: string) => `/involvements/${id}`,
    GET_BY_COMPANY: (companyId: string) => `/involvements/company/${companyId}`,
  },
  PERSON: {
    BASE: '/persons',
    GET_ALL: '/persons',
    CREATE: '/persons',
  },
};
