export const endPoints = {
  AUTH: {
    LOGIN: '/auth/login',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    LOGOUT: '/auth/logout',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
    REFRESH: '/auth/refresh',
    VERIFY_MFA: '/auth/verify-mfa', // legacy
    MFA_VERIFY: '/auth/mfa/verify',
    MFA_PREFERENCES: '/auth/mfa/preferences',
    MFA_SETUP_TOTP: '/auth/mfa/setup-totp',
    MFA_VERIFY_TOTP_SETUP: '/auth/mfa/verify-totp-setup',
    MFA_WEBAUTHN_REGISTER_CHALLENGE: '/auth/mfa/webauthn/register-challenge',
    MFA_WEBAUTHN_REGISTER_VERIFY: '/auth/mfa/webauthn/register-verify',
    MFA_WEBAUTHN_LOGIN_CHALLENGE: '/auth/mfa/webauthn/login-challenge',
  },
  ORGANIZATION: {
    BASE: '/organizations',
    GET_ALL: '/organizations',
    GET_BY_ID: (id: string) => `/organizations/${id}`,
    CREATE: '/organizations',
    UPDATE: (id: string) => `/organizations/${id}`,
    DELETE: (id: string) => `/organizations/${id}`,
    HARD_DELETE: (id: string) => `/organizations/${id}/hard`,
    ASSIGN_CUSTOM_SERVICES: (id: string) => `/organizations/${id}/custom-services`,
  },
  SERVICE_REQUEST_TEMPLATE: {
    BASE: '/service-request-templates',
    GET_ACTIVE_GENERAL: '/service-request-templates/active/general',
    GET_ACTIVE_SERVICE: (service: string) => `/service-request-templates/active/service/${service}`,
    GET_ALL: '/service-request-templates',
    GET_BY_ID: (id: string) => `/service-request-templates/${id}`,
    CREATE: '/service-request-templates',
    UPDATE: (id: string) => `/service-request-templates/${id}`,
  },
  CLIENT: {
    BASE: '/clients',
    GET_ALL: '/clients',
    GET_BY_ID: (id: string) => `/clients/${id}`,
    CREATE: '/clients',
    UPDATE: (id: string) => `/clients/${id}`,
    DELETE: (id: string) => `/clients/${id}`,
  },
  EMPLOYEES: {
    BASE: '/organization-members',
    GET_ALL: '/organization-members',
    GET_BY_ID: (id: string) => `/organization-members/${id}`,
    CREATE: '/organization-members',
    UPDATE: (id: string) => `/organization-members/${id}`,
    DELETE: (id: string) => `/organization-members/${id}`,
  },
  PLATFORM_EMPLOYEES: {
    BASE: '/platform/employees',
    GET_ALL: '/platform/employees',
    GET_BY_ID: (id: string) => `/platform/employees/${id}`,
    CREATE: '/platform/employees',
    UPDATE: (id: string) => `/platform/employees/${id}`,
    DELETE: (id: string) => `/platform/employees/${id}`,
  },
  COMPANY: {
    BASE: '/companies',
    GET_ALL: '/companies',
    GET_BY_ID: (id: string) => `/companies/${id}`,
    CREATE: '/companies',
    UPDATE: (id: string) => `/companies/${id}`,
    DELETE: (id: string) => `/companies/${id}`,
    GET_BY_CLIENT: (clientId: string) => `/companies?clientId=${clientId}`,
    INCORPORATION: (companyId: string) => `/companies/${companyId}/incorporation`,
    KYC: (companyId: string) => `/companies/${companyId}/kyc`,
    KYC_DOCUMENT_REQUEST: (kycId: string) => `/kyc/${kycId}/document-request`,

  },
  SERVICE_REQUEST: {
    BASE: '/service-requests',
    GET_ALL: '/service-requests',
    GET_BY_ID: (id: string) => `/service-requests/${id}`,
    UPDATE_STATUS: (id: string) => `/service-requests/${id}/status`,
  },
  CUSTOM_SERVICE: {
    BASE: '/custom-services',
    LIST: '/custom-services',
    GET_ACTIVE: '/custom-services/active',
    GET_BY_ID: (id: string) => `/custom-services/${id}`,
    CREATE: '/custom-services',
    UPDATE: (id: string) => `/custom-services/${id}`,
    PATCH_STATUS: (id: string) => `/custom-services/${id}/status`,
    DELETE: (id: string) => `/custom-services/${id}`,
  },
  ENGAGEMENT: {
    BASE: '/engagements',
    GET_ALL: '/engagements',
    GET_BY_ID: (id: string) => `/engagements/${id}`,
    CREATE: '/engagements',
    UPDATE: (id: string) => `/engagements/${id}`,
    UPDATE_STATUS: (id: string) => `/engagements/${id}/status`,
    UPDATE_ORGANIZATION: (id: string) => `/engagements/${id}/organization`,
  },
  LIBRARY: {
    FOLDERS: '/library/folders',
    FOLDER_CONTENT: (id: string) => `/library/folders/${id}/content`,
    ROOTS: '/library/folders/roots',
    FOLDER_BY_ID: (id: string) => `/library/folders/${id}`,
    FILES: '/library/files',
    FILE_UPLOAD: '/library/files/upload',
    FILE_BY_ID: (id: string) => `/library/files/${id}`,
    FOLDER_DOWNLOAD: (id: string) => `/library/folders/${id}/download`,
  },
  NOTICE: {
    BASE: '/notices',
    GET_ALL: '/notices',
    GET_BY_ID: (id: string) => `/notices/${id}`,
    CREATE: '/notices',
    UPDATE: (id: string) => `/notices/${id}`,
    PATCH_STATUS: (id: string) => `/notices/${id}/status`,
    DELETE: (id: string) => `/notices/${id}`,
    GET_TODAY: '/notices/today',
  },
  SUPPORT: {
    SUPPORT_REQUESTS: '/support/support-requests',
    SUPPORT_REQUEST_BY_ID: (id: string) => `/support/support-requests/${id}`,
    PATCH_SUPPORT_REQUEST: (id: string) => `/support/support-requests/${id}`,
    TICKETS: '/support/tickets',
    TICKET_BY_ID: (id: string) => `/support/tickets/${id}`,
    PATCH_TICKET: (id: string) => `/support/tickets/${id}`,
    TICKET_UPDATES: (ticketId: string) => `/support/tickets/${ticketId}/updates`,
    TICKET_UPDATE_BY_ID: (ticketId: string, id: string) => `/support/tickets/${ticketId}/updates/${id}`,
  },
  INVOLVEMENT: {
    BASE: '/involvements',
    CREATE: '/involvements',
    UPDATE: (id: string) => `/involvements/${id}`,
    DELETE: (id: string) => `/involvements/${id}`,
    GET_BY_COMPANY: (companyId: string) => `/involvements/company/${companyId}`,
  },
  PERSON: {
    BASE: '/persons',
    GET_ALL: '/persons',
    CREATE: '/persons',
  },
  DOCUMENT_REQUESTS: {
    BASE: '/document-requests',
    DOCUMENTS: (requestId: string) => `/document-requests/${requestId}/documents`,
    DOCUMENT_BY_ID: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}`,
    UPLOAD: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/upload`,
    UPLOAD_TEMPLATE: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/upload-template`,
    CLEAR: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/clear`,
    UPDATE: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}`,
    DELETE: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}`,
    STATUS: (docId: string) => `/document-requests/requested-documents/${docId}/status`,
    UPDATE_STATUS: (requestId: string) => `/document-requests/${requestId}/status`,
    ATTACH_FILES: (requestId: string, docId: string) => `/document-requests/${requestId}/documents/${docId}/attach`,
    UNASSIGNED_FILE: (requestId: string, fileId: string) => `/document-requests/${requestId}/unassigned-files/${fileId}`,
    FROM_TEMPLATE: '/document-requests/from-template',
  },
  INCORPORATION: {
    BASE: '/incorporation',
    GET_BY_COMPANY: (companyId: string) => `/incorporation/company/${companyId}`,
    UPDATE_STATUS: (id: string) => `/incorporation/${id}/status`,
    CREATE_DOCUMENT_REQUEST: (id: string) => `/incorporation/${id}/document-requests`,
  },
  PROCEDURE_PROMPT: {
    BASE: '/procedure-prompts',
    GET_ALL: '/procedure-prompts',
    GET_BY_ID: (id: string) => `/procedure-prompts/${id}`,
    CREATE: '/procedure-prompts',
    UPDATE: (id: string) => `/procedure-prompts/${id}`,
    DELETE: (id: string) => `/procedure-prompts/${id}`,
  },
  COMPLIANCE_CALENDAR: {
    BASE: '/compliance-calendar',
    LIST: '/compliance-calendar',
    GET_BY_ID: (id: string) => `/compliance-calendar/${id}`,
    CREATE: '/compliance-calendar',
    UPDATE: (id: string) => `/compliance-calendar/${id}`,
    DELETE: (id: string) => `/compliance-calendar/${id}`,
  },
  PLATFORM_ANALYTICS: {
    OVERVIEW: '/platform/analytics/overview',
  },
  NOTIFICATION: {
    BASE: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
    MARK_READ: (id: string) => `/notifications/read/${id}`,
    MARK_ALL_READ: '/notifications/read-all',
    PREFERENCES: '/notifications/preferences',
  },

  TEMPLATE: {
    BASE: '/templates',
    GET_ALL: '/templates',
    GET_BY_ID: (id: string) => `/templates/${id}`,
    CREATE: '/templates',
    UPDATE: (id: string) => `/templates/${id}`,
    DELETE: (id: string) => `/templates/${id}`,
    HARD_DELETE: (id: string) => `/templates/${id}/hard`,
    UPLOAD_FOLDER: '/templates/upload-folder',
  },

  QUICKBOOK: {
    CONNECT: '/accounting/quickbooks/connect',
    CONNECT_URL: (companyId: string, clientId?: string) =>
      `/accounting/quickbooks/connect?companyId=${encodeURIComponent(companyId)}${clientId ? `&clientId=${encodeURIComponent(clientId)}` : ''}`,
    REVOKE: (companyId: string) => `/companies/${companyId}/accounting/quickbooks/revoke`,
  }
};
